inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "vagrant/**/*"
    - "vendor/**/*"
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/FormatString:
  EnforcedStyle: sprintf

Style/SymbolArray:
  Enabled: false
